### ISSUE TITLE
images: 500 Internal Server Error

### ISSUE THREAD

**Issue by Slinky-Wrangle-Punch** [open-eats/OpenEats#138]
I'm using the docker version. Everything is working, BUT:

The custom food images aren't loading. Even in the admin page I get an "500 Internal Server Error" if I want to open the image directly (e.g. with the path /site-media/upload/recipe_photos/example-image.png)

Did I get some settings wrong or this a bug?

my env_prod.list:

```
# Database config
MYSQL_DATABASE=openeats
MYSQL_ROOT_PASSWORD=***pwd***

# Django config
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=**key**
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=*
HTTP_X_FORWARDED_PROTO=true

# Node config
NODE_ENV=production
NODE_URL=localhost:8080
NODE_LOCALE=de
```

my docker-prod.override.yml:

```
version: '2.3'
services:
  nginx:
    restart: always
    ports:
      - "7000:80" 
  api:
    restart: always
  web:
    restart: on-failure
  db:
    restart: always
```
