### ISSUE TITLE
OpenEats Doesn't Auto-Start at System Boot/Restart

### ISSUE THREAD

**Issue by jnikolich** [open-eats/OpenEats#58]
(This isn't so much an issue, as a documentation enhancement request)

It appears that, by default, OpenEats will not auto-start whenever the Docker host is booted, and/or when Docker is fired up.

I found that I could cause auto-starting to happen correctly (at least for me) with the following definitions in my `docker-prod.override.yml` file:
#### docker-prod.override.yml
````
version: '2.3'
services:
  nginx:
    ports:
        - "8000:80"
    restart: always
  api:
    restart: always
  web:
    restart: on-failure
  db:
    restart: always
````
### Notes/Comments
1. The `ports:` stanza for nginx represents what I need in my system.  Obviously, you'll want to customize this to your particular needs, assuming you require it at all.
2. I found that under normal circumstances, the `web` container appears to be a "run-once" kind of thing.  When you start OpenEats it will fire up, and terminate (presumally successfully).  As this seems to be desired behaviour I set it to `restart: on-failure` instead of `always` as is done for the other containers.

Submitted in the hopes that this helps others looking to implement similar auto-start behaviour.
